models/Post.php
<?php

namespace app\models;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "post".
 *
 * @property int $id
 * @property string $title
 * @property string|null $lead
 * @property string|null $text
 * @property int|null $created_ad
 */
class Post extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'post';
    }

    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'created_ad',
                'updatedAtAttribute' => false,
                'value' => time(),
            ]
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['title'], 'required'],
            [['text'], 'string'],
            [['created_ad'], 'integer'],
            [['title'], 'string', 'max' => 50],
            [['lead'], 'string', 'max' => 150],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Заголовок',
            'lead' => 'Описание',
            'text' => 'Текст',
            'created_ad' => 'Дата создания',
        ];
    }

    public static function PostById($id)
    {
       return self::find()->where(['id' => $id])->one();
    }
}

controllers/PostController.php
<?php

namespace app\controllers;

use app\models\PostSearch;
use Yii;
use yii\web\Controller;
use app\models\Post;
use yii\web\NotFoundHttpException;
use app\models\PostFrontendSearch;

class PostController extends Controller
{


    public function actionIndex()
    {
        $searchModel = new PostFrontendSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel
            ]);
    }
    public function actionView($id)
    {
        $post = Post::PostById($id);
        if ($post) {
            return $this->render('view', ['model' => $post]);
        }
        throw new NotFoundHttpException('Пост не найден!');
    }
}

views/post/_viewItem.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;

?>
<div class="row">
    <h2>
        <?= Html::a($model['title'], Url::toRoute(['post/view', 'id' => $model['id']])); ?>
    </h2>
    <p>
        <?= $model['text']; ?>
    </p>
</div>

views/post/index.php
<?php

    use yii\helpers\ArrayHelper;
    use yii\widgets\ListView;

    use yii\helpers\Html;
    use yii\widgets\ActiveForm;

    $this->title = 'Все посты';

    $searchString = ArrayHelper::getValue(yii::$app->request->queryParams, 'PostFrontendSearch.text');
    if($searchModel){
        $this->title = 'Результаты поиска';
    }

    $testString = 'it`s test!';

    $script =<<< JS
        $(function() {
            alert('Hello from view! ' + "$testString");
        });
JS;
$this->registerJs($script, \yii\web\View::POS_READY);

?>

<div class="row">
    <?php $form = ActiveForm::begin([
            'method' => 'get',
    ]); ?>

    <div class="col-sm-12 col-md-1">
        Поиск
    </div>

    <div class="col-sm-12 col-md-3">
        <?= $form -> field($searchModel, 'text')
            ->textInput(['placeholder' => 'Введите строку для поиска'])
            ->label(false);
        ?>
    </div>

    <div class="col-sm-12 col-md-1">
        <?= Html::submitButton('Искать', ['class' => 'btn btn-primary']) ?>
    </div>
        <?php ActiveForm::end(); ?>
</div>

    <?php if($searchString): ?>
        <h1>Вы искали: "<?= Html::encode($searchString); ?>"</h1>
    <?php else: ?>
        <h1>Все посты</h1>
    <?php endif; ?>

<section>
    <?php
    echo ListView::widget([
     'dataProvider' => $dataProvider,
     'itemView' => '_viewItem',
    ]); ?>
</section>

views/post/view.php
<?php
    $this->title = $model->title;
?>
<article>
    <p>
        <?= date('d.m.Y', $model->created_ad)?>
    </p>
    <h1>
        <?= $model['title']; ?>
    </h1>
    <p>
        <?= $model['text']; ?>
    </p>
</article>